---
- name: Upgrade system
  yum:
    name: "*"
    state: latest
    update_cache: yes
  when: common_upgrade_system | bool == True

- name: Ensure firewalld disabled
  systemd:
    name: firewalld.service
    state: stopped
    enabled: false
    daemon_reload: yes

- name: Ensure timezone is Asia/Shanghai
  file:
    src: /usr/share/zoneinfo/Asia/Shanghai
    dest: /etc/localtime
    state: link

- name: Install libselinux-python
  yum:
    name: libselinux-python
    state: installed

- name: Ensure selinux disabled
  selinux:
    state: disabled
  register: se

- name: Reboot if selinux needed
  shell: sleep 2 && shutdown -r now "reboot for disable selinux"
  async: 1
  poll: 0
  ignore_errors: yes
  when: se.reboot_required
  tags:
    - reboot

- name: Waitting for reconnecting
  wait_for_connection:
    dalay: 5
  when: se.reboot_required | bool == True
  tags:
    - reboot