---
- name: Upgrade system
  yum:
    name: "*"
    state: latest
    update_cache: yes
  when: common_upgrade_system | bool == True
  tags:
    - upgrade_system

- name: Install epel-release
  yum:
    name: epel-release
    state: present
    update_cache: yes
  tags:
    - always

- name: Ensure firewalld disabled
  systemd:
    name: firewalld.service
    state: stopped
    enabled: false
    daemon_reload: yes
  tags:
    - firewalld

- name: Ensure timezone is Asia/Shanghai
  file:
    src: /usr/share/zoneinfo/Asia/Shanghai
    dest: /etc/localtime
    state: link
  tags:
    - timezone

- name: Setting sysctl.conf
  copy:
    src: sysctl.conf
    dest: /etc/sysctl.conf
    backup: true
  tags:
    - sysctl
  notify:
    - apply sysctl

- name: Install libselinux-python
  yum:
    name: libselinux-python
    state: installed
  tags:
    - selinux

- name: Ensure selinux disabled
  selinux:
    state: disabled
  register: se
  tags:
    - selinux
  notify:
    - reboot
